core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('detail/<int:pk>/', views.ArticleDetailView.as_view(), name='detail'),
    path('article-create/', views.ArticleCreateView.as_view(), name='article-create'),
    path('article-edit/<int:pk>/', views.ArticleEditView.as_view(), name='article-edit'),
    path('category/<str:inner_name>/', views.CategoryDetailView.as_view(), name='category-detail'),
    path('category-create/', views.CategoryCreateView.as_view(), name='category-create'),
    path('category-edit/<str:inner_name>', views.CategoryEditView.as_view(), name='category-edit'),
    path('user-edit/', views.UserEditView.as_view(), name='user-edit'),
    path('user-detail/', views.UserDetailView.as_view(), name='user-detail'),
    path('author-list/', views.AuthorListView.as_view(), name='author-list'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve
import os

urlpatterns = [
    path(f'{os.getenv("ADMIN_PATH") or "admin"}/', admin.site.urls),
    path('', include("core.urls")),
    path('accounts/', include('allauth.urls')),
    path('editorjs/', include('django_editorjs_fields.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

# Django側からの配信はDEBUG時のみ、そうでないときはNginxから行う
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.core.validators import RegexValidator
from django_editorjs_fields import EditorJsTextField
from django.conf import settings
import json
import textwrap  # html整形のため
import re # パラグラフやリストの中にhtml要素を記述するため

alphanumeric = RegexValidator(r'^[0-9a-zA-Z_]*$', '半角英数字とアンダースコアのみ使用可能です。')  # 内部カテゴリ名として半角英数字とアンダースコアしか使えないようにする

def local_now():
    return timezone.localtime(timezone.now())

class MyUser(AbstractUser):
    # usernameとemailはすでにAbstractUserで定義済み,passwordはすでにAbstractBaseUserで定義済み
    icon = models.ImageField('アイコン画像', upload_to='icons/', default='default/default_user_icon.png')
    pub_date = models.DateTimeField('登録日', default=local_now)
    display_name = models.CharField('表示名', max_length=100, default='表示名')
    description = models.TextField('自己紹介文', max_length=2000, default='これが作者の紹介文です。')
    def __str__(self):
        return self.display_name


class Category(models.Model):
    upper = models.ForeignKey('self', verbose_name='上位カテゴリ', on_delete=models.PROTECT, blank=True, null=True, related_name='lowers')  # 上位カテゴリは、そのカテゴリに属するカテゴリを全て削除しない限り削除できない
    name = models.CharField('カテゴリ名', max_length=100, unique=True)
    inner_name = models.CharField('内部カテゴリ名', max_length=100, validators=[alphanumeric], unique=True)
    description = models.TextField('カテゴリの説明文', blank=False, null=False, default='これがカテゴリの説明文です。')
    is_root = models.BooleanField('ナビゲーションに表示するかどうか', default=False, help_text='最上位のカテゴリは必ず表示する必要があります。')  # ルートカテゴリは大きいカテゴリであることを示す

    def __str__(self):
        return self.name


class Article(models.Model):
    thumbnail = models.ImageField('サムネイル画像', upload_to='thumbnails/%Y/%m/%d/', default='default/default_thumbnail.png')
    pub_date = models.DateTimeField('投稿日', default=local_now)
    renew_date = models.DateTimeField('更新日', default=local_now)
    title = models.CharField('タイトル', max_length=200)
    view_count = models.IntegerField('PV数', default=0)  # 約21億が上限。さすがにそこまではいかないだろう
    category = models.ForeignKey(Category, verbose_name='カテゴリ', on_delete=models.PROTECT, default=1)  # カテゴリは、そのカテゴリに属する記事を全て削除しない限り削除できない
    author = models.ForeignKey(MyUser, verbose_name='作者', on_delete=models.SET_DEFAULT, default=1)  # 作者が削除されると、記事はすべて管理者(id=1)のものになる
    lead = models.TextField('リード文', max_length=2000, blank=True, default='', help_text='投稿日や作者の直後で目次（表示する場合）の直前に挿入される文章です。リード文は記事のリンクにも使われます。')
    has_table_of_contents = models.BooleanField('目次を表示するかどうか', default=False)
    is_published = models.BooleanField('公開するかどうか', default=True)
    # contentとcontent_as_htmlを分けることで、記事の読み込み時にいちいちjsonからパースする必要がなくなる
    # 通常はcontentを編集し、その内容を自動的にcontent_as_htmlに書き出す
    content = EditorJsTextField(verbose_name='内容',blank=True)
    content_as_html = models.TextField('内容のHTML', max_length=1000000, null=False, blank=True, default='', help_text='html要素からは編集しないでください。このフィールドの変更は自動制御されているので、上書きされます。htmlを編集したい場合、editor.jsのraw要素を使ってください。')

    def __str__(self):
        return self.title

    def compose_html(self):
        """EditorJsTextFieldをHTMLにする"""
        content = json.loads(self.content)
        result = ''

        def list_to_html(depth, dict_list):
            if dict_list:
                result = '\t' * (2 * depth - 3) + f'<{"ol" if depth == 2 else "ul"} class="toc-{"ol" if depth == 2 else "ul"} level{depth}">\n'
                index = 0
                n = len(dict_list)
                while index < n:
                    result += '\t' * (2 * depth - 2) + '<li class="toc-li">\n'
                    result += '\t' * (2 * depth - 1) + f'<a href="#{dict_list[index]["id"]}" class="toc-a">{dict_list[index]["data"]["text"]}</a>' + '\n'
                    index += 1
                    sub_list = []
                    while index < n and dict_list[index]['data']['level'] != depth:
                        sub_list += [dict_list[index]]
                        index += 1
                    result += list_to_html(depth + 1, sub_list)
                    result += '\t' * (2 * depth - 2) + '</li>\n'
                result += "\t" * (2 * depth - 3) + f'</{"ol" if depth == 2 else "ul"}>\n'
                return result
            return ''
        
        if self.has_table_of_contents:
            headers = list(filter(lambda block: block['type'] == 'Header', content['blocks']))
            toc = list_to_html(2, headers)
            result += f'<div class="toc-container">\n\t<p class="toc-title">Contents</p>\n{toc}</div>\n'
        for block in content['blocks']:
            element = ''
            match block['type']:
                case 'Header':
                    element = f"""
                    <h{block['data']['level']} id="{block['id']}">
                        {block['data']['text']}
                    </h{block['data']['level']}>
                    """
                case 'Image':
                    element = f"""
                    <figure>
                        <img class="content-image" src="{block['data']['file']['url']}">
                        <figcaption class="content-image-caption">
                            {block['data']['caption']}
                        </figcaption>
                    </figure>
                    """
                case 'Math':
                    element = f"""
                    <div class="equation-container">
                        \\[{block['data']['text']}\\]
                    </div>
                    """
                case 'paragraph':
                    element = f"""
                    <p>{block['data']['text']}</p>
                    """
                case 'List':
                    class_name = 'ol' if block['data']['style'] == 'ordered' else 'ul'
                    element = f'\n<{class_name}>\n'
                    for item in block['data']['items']:
                        element += f'\t<li>{item}</li>\n'
                    element += f'</{class_name}>\n'
                case 'Code':
                    # pre要素の内部なので整形困難
                    element = f'\n<blockquote><pre><code class="code">{block["data"]["code"]}</code></pre></blockquote>\n'
                case 'Raw':
                    element = '\n<div class="raw-html-container">\n'
                    for line in block['data']['html'].splitlines():
                        element += f'\t{line}\n'
                    element += '</div>\n'
                case 'Table':
                    data = block['data']['content']
                    element = '\n<table class="article-table">\n'
                    for row in range(len(data)):
                        element += f'\t<tr>\n'
                        for column in range(len(data[row])):
                            element += f'\t\t<td>{data[row][column]}</td>\n'
                        element += f'\t</tr>\n'
                    element += '</table>\n'
                case 'Checklist':
                    element = '\n<ul class="checklist">\n'
                    for item in block['data']['items']:
                        element += f'\t<li checked="{item["checked"]}">{item["text"]}</li>\n'
                    element += '</ul>\n'
                case 'Delimiter':
                    element = f"""
                    <hr class="delimiter">
                    """
                case 'Quote':
                    element = f"""
                    <div>
                        <blockquote class="quote">{block['data']['text']}</blockquote>
                        <p class="quote-caption">{block['data']['caption']}</p>
                    </div>
                    """
                case 'Warning':
                    element = f"""
                    <div class="warning-container">
                        <p class="warning-title">
                            <i class="fa-solid fa-triangle-exclamation"></i>
                            {block['data']['title']}</p>
                        <div class="warning-message">
                            {block['data']['message']}
                        </div>
                    </div>
                    """
                case 'LinkTool':
                    element = f"""
                    <a class="external-link-block" href="{block['data']['link']}">
                        <div class="external-link-title">
                            <i class="fa-solid fa-arrow-up-right-from-square"></i>
                            {block['data']['meta']['title']}
                        </div>
                        <p class="external-link-description">
                            {block['data']['meta']['description']}
                        </p>
                        <span class="external-link-url">
                            {block['data']['link']}
                        </span>
                    </a>
                    """
                case _ as str:
                    element = f"""
                    <p style="color: red;">規定のタイプ以外の要素が検出されました：{str}</p>
                    """
            result += textwrap.dedent(element)[:-1]  # 一番浅いインデントを0にして、最後の改行を削除
        exp = r'&lt;(.{1,5})&gt;'
        self.content_as_html = re.sub(exp, r'<\1>', result)
        # セーブは行わないので、compose_htmlを実行した後セーブする必要がある

core/forms.py
from django import forms
from .models import Article, Category, MyUser
from django_editorjs_fields import EditorJsWidget
from django.conf import settings

class ArticleEditForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'thumbnail', 'content', 'category', 'has_table_of_contents', 'is_published', 'lead']
        widgets = {
            'content': EditorJsWidget(
                config={'minHeight': 300}
            ),
        }


class CategoryEditForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['upper', 'name', 'inner_name', 'description', 'is_root']
    
    def clean_upper(self):
        # データベースには保存せずに、モデルのオブジェクトを取得
        # viewでインスタンスを編集元に指定しているので、pkを取得できる
        default_pk = self.save(commit=False).pk
        category = self.cleaned_data['upper']
        i = 0  # 無限ループを防止するための変数
        while i < 100 and category is not None:
            i += 1
            pk = category.pk
            if pk == default_pk:
                raise forms.ValidationError('カテゴリ木がループしています。カテゴリのグラフは有向木である必要があります。')
            category = category.upper
        return self.cleaned_data['upper']
    
    def clean_is_root(self):
        is_root = self.cleaned_data['is_root']
        if 'upper' in self.cleaned_data:  # clean_upper()でupperが生き残っていない可能性を考慮
            upper = self.cleaned_data['upper']
            if upper is None and not is_root:
                raise forms.ValidationError('上位カテゴリを指定しない場合、カテゴリは必ずルートカテゴリである必要があります。')
        return is_root


class UserEditForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ['icon', 'username', 'display_name', 'description']

core/templates/core/article_create.html
{% extends 'core/base/one_column_base.html' %}
{% load static %}
{% block title %}記事新規作成{% endblock %}
{% block extra-styles %}
{{ block.super }}
{{ form.media }}
<link rel="stylesheet" href="{% static 'core/css/edit_base.css' %}">
<link rel="stylesheet" href="{% static 'core/css/article_edit.css' %}">
{% endblock %}
{% block column1-1 %}
{% include 'core/breadcrumb_list.html' with title='記事新規作成' is_published=True %}
<h1>記事新規作成</h1>
{% if user.is_authenticated %}
{% if form.errors %}
<p class="error-notification">以下のエラー箇所を修正してください。</p>
{{ form.errors }}
{% endif %}
<form method="post" action="{% url 'core:article-create' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <h2>基本情報</h2>
    <table>
        <tr>
            <td><label for="title">カテゴリ：</label></td>
            <td>{{ form.category }}</td>
        </tr>
        <tr>
            <td><label for="title">タイトル：</label></td>
            <td>{{ form.title }}</td>
        </tr>
        <tr>
            <td><label for="thumbnail">サムネイル画像：</label></td>
            <td>{{ form.thumbnail }}</td>
        </tr>
        <tr>
            <td>作者表示名：</td>
            <td>{{ user.display_name }}</td>
        </tr>
        <tr>
            <td>リード文：</td>
            <td>{{ form.lead }}</td>
        </tr>
        <tr>
            <td>目次を表示する：</td>
            <td>{{ form.has_table_of_contents }}</td>
        </tr>
        <tr>
            <td>記事を公開する：</td>
            <td>{{ form.is_published }}</td>
        </tr>
    </table>
    ※ほかの作者で作成する場合は、一度ログアウトし、そのアカウントでログインしなおしてください。
    <h2>内容</h2>
    ※タイトルとサムネイル画像の後の本文から書いてください。<br>
    {{ form.content }}
    <button type="submit" class="post-button">この内容で投稿</button>
</form>
{% else %}
<p>現在ログイン中でないので、ここに表示する内容はありません。</p>
{% endif %}
{% endblock %}

core/templates/core/article_detail.html
{% extends "core/base/two_column_base.html" %}
{% load static %}
{% load make_indent %}
{% load editorjs %}
{% block title %}{{article.title}}{% endblock %}
{% block extra-styles %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'core/css/article_detail.css' %}">
<link rel="stylesheet" type="text/css" href="https://tikzjax.com/v1/fonts.css">
{% endblock %}
{% block column2-1 %}
{% include 'core/breadcrumb_list.html' with category_list=category_list title=article.title
is_published=article.is_published %}
<article>
    <h1 class="title">{{article.title}}</h1>
    <div class="article-info">
        <div class="row1">
            <div class="article-view-count">{{article.view_count}} views</div>
            <div class="article-dates">
                <time class="article-pub-date" datetime="{{ article.pub_date|date:'c' }}">
                    <i class="fa-regular fa-clock"></i>&nbsp;{{ article.pub_date|date:'Y/m/d' }}
                </time>
                <time class="article-renew-date" datetime="{{ article.renew_date|date:'c' }}">
                    <i class="fa-solid fa-clock-rotate-left"></i>&nbsp;{{ article.renew_date|date:'Y/m/d' }}
                </time>
            </div>
        </div>
        <div class="row2">
            <div class="article-author"><i class="fa-solid fa-pen-nib"></i>&nbsp;{{ article.author.display_name }}</div>
        </div>
    </div>
    <figure>
        <img class="thumbnail-image" src="{{article.thumbnail.url}}" alt="{{article.title}}">
    </figure>
    {% if article.lead %}
    <p class="lead_sentence">{{article.lead}}</p>
    {% endif %}
    <div id="article-content" class="article-content">
        {{ article.content_as_html|safe }}
    </div>
</article>
{% if user.id == article.author.id %}
<hr class="delimiter">
<p style="text-align: center;">※以下の内容は作者としてログイン中のため表示されています。</p>
<details>
    <summary>
        <h2>このページのJSONデータ</h2>
    </summary>
    <pre class="article-json-data" id="article-json-data">{{ article.content|make_indent:2 }}</pre>
</details>
<br>
<div class="article-edit-button-container">
    <a href="{% url 'core:article-edit' article.pk %}" class="article-edit-link">
        この記事を編集する
    </a>
</div>
{% endif %}
{% endblock %}
{% block scripts %}
<!-- The loading of KaTeX is deferred to speed up page rendering -->
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.2/dist/katex.min.js"
    integrity="sha384-Qsn9KnoKISj6dI8g7p1HBlNpVx0I8p1SvlwOldgi3IorMle61nQy4zEahWYtljaz"
    crossorigin="anonymous"></script>
<!-- To automatically render math in text elements, include the auto-render extension: -->
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.2/dist/contrib/auto-render.min.js"
    integrity="sha384-+VBxd3r6XgURycqtZ117nYw44OOcIax56Z4dCRWbxyPt0Koah1uHoK0o4+/RRE05" crossorigin="anonymous"
    onload="renderMathInElement(document.body);"></script>
<script type="text/javascript" src="{% static 'core/js/article_compose.js' %}"></script>
{{ block.super }}
{% endblock %}

core/templates/core/article_edit.html
{% extends 'core/base/one_column_base.html' %}
{% load static %}
{% block title %}記事編集{% endblock %}
{% block extra-styles %}
{{ block.super }}
{{ form.media }}
<link rel="stylesheet" href="{% static 'core/css/edit_base.css' %}">
<link rel="stylesheet" href="{% static 'core/css/article_edit.css' %}">
{% endblock %}
{% block column1-1 %}
{% include 'core/breadcrumb_list.html' with title='記事編集' is_published=True %}
<h1>記事編集</h1>
{% if user.is_authenticated %}
{% if user.id == article.author.pk %}
{% if form.errors %}
<p class="error-notification">以下のエラー箇所を修正してください。</p>
{{ form.errors }}
{% endif %}
<form method="post" action="{% url 'core:article-edit' pk=article.pk %}" enctype="multipart/form-data">
    {% csrf_token %}
    <h2>基本情報</h2>
    <table>
        <tr>
            <td><label for="id_category">カテゴリ：</label></td>
            <td>{{ form.category }}</td>
        </tr>
        <tr>
            <td><label for="id_title">タイトル：</label></td>
            <td>{{ form.title }}</td>
        </tr>
        <tr>
            <td><label for="id_thumbnail">サムネイル画像：</label></td>
            <td>{{ form.thumbnail }}</td>
        </tr>
        <tr>
            <td>作者表示名：</td>
            <td>{{ user.display_name }}</td>
        </tr>
        <tr>
            <td><label for="id_lead">リード文：</label></td>
            <td>{{ form.lead }}</td>
        </tr>
        <tr>
            <td><label for="id_has_table_of_contents">目次を表示する：</label></td>
            <td>{{ form.has_table_of_contents }}</td>
        </tr>
        <tr>
            <td><label for="id_is_published">記事を公開する：</label></td>
            <td>{{ form.is_published }}</td>
        </tr>
    </table>
    <h2>内容</h2>
    ※タイトルとサムネイル画像の後の本文から書いてください。<br>
    {{ form.content }}
    <button type="submit" class="post-button">変更を適用する</button>
</form>
{% else %}
<p>現在ログイン中のユーザーはこの記事の筆者ではないので、ここに表示する内容はありません。</p>
{% endif %}
{% else %}
<p>現在ログイン中でないので、ここに表示する内容はありません。</p>
{% endif %}
{% endblock %}
{% block scripts %}
<script type="text/javascript">  // &のエスケープを戻す
    document.addEventListener('DOMContentLoaded', () => {
        setTimeout(() => {
            let inputs = document.querySelectorAll('input.text-node');
            inputs.forEach((input) => {
                input.value = input.value.replaceAll('&amp;', '&');
            });
        }, 1000);
    })
</script>
{{ block.super }}
{% endblock %}

core/templates/core/article_link.html
<a href="{% url 'core:detail' article.pk %}" class="article-link" rel="bookmark">
    <div class="article-link-container">
        <div class="article-link-thumbnail-container">
            <figure>
                <img class="article-link-thumbnail" src="{{article.thumbnail.url}}" alt="{{article.thumbnail.alt}}">
            </figure>
        </div>
        <div class="article-link-description">
            <p class="article-link-title">{{ article.title }}</p>
            <p class="article-link-lead">{{ article.lead }}</p>
        </div>
    </div>
</a>

core/templates/core/breadcrumb_list.html
<div class="breadcrumb-list">
    <a class="crumb-list-item" href="{% url 'core:index' %}">
        <i class="fa-solid fa-house"></i>
        HOME
    </a>
    {% for category in category_list %}
    &gt;
    <a class="crumb-list-item" href="{% url 'core:category-detail' category.inner_name %}" rel="category">
        <i class="fa-regular fa-folder"></i>
        {{ category.name }}
    </a>
    {% endfor %}
    {% if title %}
    &gt;
    <a class="crumb-list-item" href="#">{{ title }}{% if not is_published %}<small><span
                class="not-published-notification">*未公開</span></small>{% endif %}</a>
    {% endif %}
    <!-- htmlの改行でスペースがひとつ入ってしまうのでそれを見越して省略する -->
</div>

core/templates/core/category.html
{% extends 'core/base/two_column_base.html' %}
{% load static %}
{% block title %}{{ category.name }}{% endblock %}
{% block extra-styles %}
    <link rel="stylesheet" href="{% static 'core/css/category.css' %}">
{% endblock %}
{% block column2-1 %}
    <div class="breadcrumb-list">
        <a class="crumb-list-item" href="{% url 'core:index' %}">
            <i class="fa-solid fa-house"></i>
            HOME
        </a>
        {% for category in category_list %}
        >&nbsp;<a class="crumb-list-item" href="{% url 'core:category' category.inner_name %}">{{ category.name }}</a>
        {% endfor %}
        <!-- htmlの改行でスペースがひとつ入ってしまうのでそれを見越して省略する -->
    </div>
    <h1>カテゴリ：{{ category.name }}</h1>
    <p class="category-description">
        {{ category.description }}
    </p>
    <h2>{{ category.name }}カテゴリの記事一覧</h2>
    {% for article in articles %}
        {% include 'core/article_link.html' with article=article %}
    {% endfor %}
    <h2>{{ category.name }}カテゴリの下位カテゴリ一覧</h2>
    <div class="lower-categories">
        {% for lower_category in lower_categories %}
            <a href="{% url 'core:category' lower_category.inner_name %}" class="lower-category-link">
                <div class="lower-category-container">
                    <h3>{{ lower_category.name }}</h3>
                    <p class="category-description">
                        {{ lower_category.description }}
                    </p>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}

core/templates/core/category_detail.html
{% extends 'core/base/two_column_base.html' %}
{% load static %}
{% block title %}{{ category.name }}{% endblock %}
{% block extra-styles %}
<link rel="stylesheet" href="{% static 'core/css/category_detail.css' %}">
{% endblock %}
{% block column2-1 %}
{% include 'core/breadcrumb_list.html' with category_list=category_list %}
<h1>カテゴリ：{{ category.name }}</h1>
<p class="category-description">
    {{ category.description }}
</p>
{% if lower_categories %}
<h2>{{ category.name }}カテゴリの下位カテゴリ一覧</h2>
<div class="lower-categories">
    {% for lower_category in lower_categories %}
    <a href="{% url 'core:category-detail' lower_category.inner_name %}" class="lower-category-link">
        <div class="lower-category-container">
            <h3><i class="fa-regular fa-folder"></i>&nbsp;{{ lower_category.name }}</h3>
            <p class="category-description">
                {{ lower_category.description }}
            </p>
        </div>
    </a>
    {% endfor %}
</div>
{% endif %}
<h2>{{ category.name }}カテゴリの記事一覧</h2>
{% if articles %}
<div class="article-links">
    {% for article in articles %}
    {% include 'core/article_link.html' with article=article %}
    {% endfor %}
</div>
{% else %}
<p><mark>このカテゴリの記事はまだ無いようです。</mark></p>
{% endif %}
{% if user.is_staff %}
<div class="category-edit-button-container">
    <a href="{% url 'core:category-edit' category.inner_name %}" class="category-edit-link">
        このカテゴリを編集する
    </a>
</div>
{% endif %}
{% endblock %}

core/templates/core/category_edit.html
{% extends 'core/base/one_column_base.html' %}
{% load static %}
{% block title %}カテゴリ{% if creating_new %}新規作成{% else %}編集{% endif %}{% endblock %}
{% block extra-styles %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'core/css/edit_base.css' %}">
{% endblock %}
{% block column1-1 %}
{% include 'core/breadcrumb_list.html' with title='カテゴリ新規作成・編集' is_published=True %}
<h1>カテゴリ{% if creating_new %}新規作成{% else %}編集{% endif %}</h1>
{% if user.is_staff %}
{% if form.errors %}
<p class="error-notification">以下のエラー箇所を修正してください。</p>
{{ form.errors }}
{% endif %}
{% if creating_new %}
<form method="post" action="{% url 'core:category-create' %}">
    {% else %}
    <form method="post" action="{% url 'core:category-edit' inner_name=inner_name %}">
        {% endif %}
        {% csrf_token %}
        <h2>基本情報</h2>
        <table>
            <tr>
                <td><label for="id_upper">上位カテゴリ：</label></td>
                <td>{{ form.upper }}</td>
            </tr>
            <tr>
                <td><label for="id_name">カテゴリ名：</label></td>
                <td>{{ form.name }}</td>
            </tr>
            <tr>
                <td><label for="id_inner_name">内部カテゴリ名：</label></td>
                <td>{{ form.inner_name }}</td>
            </tr>
            <tr>
                <td><label for="id_description">説明文：</label></td>
                <td>{{ form.description }}</td>
            </tr>
            <tr>
                <td><label for="id_is_root">ルートカテゴリかどうか：</label></td>
                <td>{{ form.is_root }}</td>
            </tr>
        </table>
        <button type="submit" class="post-button">{% if creating_new %}この内容で作成{% else %}変更を適用する{% endif %}</button>
    </form>
    {% else %}
    <p>現在スタッフユーザーでログイン中でないので、ここに表示する内容はありません。</p>
    {% endif %}
    {% endblock %}

core/templates/core/user_detail.html
{% extends 'core/base/two_column_base.html' %}
{% load static %}
{% block title %}アカウント{% endblock %}
{% block extra-styles %}
<link rel="stylesheet" href="{% static 'core/css/user_detail.css' %}">
{% endblock %}
{% block column2-1 %}
{% include 'core/breadcrumb_list.html' with title='マイページ' is_published=True %}
<h1>{{ user.display_name }}のマイページ</h1>
<div class="user-info">
    <div class="user-info-left">
        <img class="user-icon" src="{{ user.icon.url }}">
    </div>
    <div class="user-info-right">
        <div class="info-label">表示名：</div>
        <div class="info-data">{{ user.display_name }}</div>
        <div class="info-label">ユーザー名：</div>
        <div class="info-data">{{ user.username }}</div>
        <div class="info-label">登録日：</div>
        <div class="info-data">{{ user.pub_date }}</div>
        <div class="info-label">自己紹介文：</div>
        <div class="info-data">{{ user.description }}</div>
    </div>
</div>
<div class="user-edit-button-container">
    <a href="{% url 'core:user-edit' %}" class="user-edit-link">
        プロフィール編集
    </a>
    <a href="{% url 'account_change_password' %}" class="user-edit-link">
        パスワード変更
    </a>
</div>
{% if articles %}
<h2>{{ user.display_name }}の記事一覧</h2>
<div class="articles">
    <table class="articles-table">
        <tr>
            <th>
                タイトル
            </th>
            <th>
                更新日
            </th>
            <th>
                PV数
            </th>
            <th>
                公開状況
            </th>
        </tr>
        {% for article in articles %}
        <tr>
            <td>
                <a href="{% url 'core:detail' article.pk %}">
                    {{ article.title }}
                </a>
            </td>
            <td>
                {{ article.renew_date }}
            </td>
            <td>
                {{ article.view_count }}
            </td>
            <td>
                {% if article.is_published %}公開中{% else %}未公開{% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endif %}
{% endblock %}