core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('detail/<int:pk>/', views.ArticleDetailView.as_view(), name='detail'),
    path('article-create/', views.ArticleCreateView.as_view(), name='article-create'),
    path('article-edit/<int:pk>/', views.ArticleEditView.as_view(), name='article-edit'),
    path('category/<str:inner_name>/', views.CategoryDetailView.as_view(), name='category-detail'),
    path('category-create/', views.CategoryCreateView.as_view(), name='category-create'),
    path('category-edit/<str:inner_name>', views.CategoryEditView.as_view(), name='category-edit'),
    path('user-edit/', views.UserEditView.as_view(), name='user-edit'),
    path('user-detail/', views.UserDetailView.as_view(), name='user-detail'),
    path('author-list/', views.AuthorListView.as_view(), name='author-list'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve
import os

urlpatterns = [
    path(f'{os.getenv("ADMIN_PATH") or "admin"}/', admin.site.urls),
    path('', include("core.urls")),
    path('accounts/', include('allauth.urls')),
    path('editorjs/', include('django_editorjs_fields.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

# Django側からの配信はDEBUG時のみ、そうでないときはNginxから行う
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from .models import Article, Category, MyUser
from django_editorjs_fields import EditorJsWidget
from django.conf import settings

class ArticleEditForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'thumbnail', 'content', 'category', 'has_table_of_contents', 'is_published', 'lead']
        widgets = {
            'content': EditorJsWidget(
                config={'minHeight': 300}
            ),
        }


class CategoryEditForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['upper', 'name', 'inner_name', 'description', 'is_root']
    
    def clean_upper(self):
        # データベースには保存せずに、モデルのオブジェクトを取得
        # viewでインスタンスを編集元に指定しているので、pkを取得できる
        default_pk = self.save(commit=False).pk
        category = self.cleaned_data['upper']
        i = 0  # 無限ループを防止するための変数
        while i < 100 and category is not None:
            i += 1
            pk = category.pk
            if pk == default_pk:
                raise forms.ValidationError('カテゴリ木がループしています。カテゴリのグラフは有向木である必要があります。')
            category = category.upper
        return self.cleaned_data['upper']
    
    def clean_is_root(self):
        is_root = self.cleaned_data['is_root']
        if 'upper' in self.cleaned_data:  # clean_upper()でupperが生き残っていない可能性を考慮
            upper = self.cleaned_data['upper']
            if upper is None and not is_root:
                raise forms.ValidationError('上位カテゴリを指定しない場合、カテゴリは必ずルートカテゴリである必要があります。')
        return is_root


class UserEditForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ['icon', 'username', 'display_name', 'description']

core/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.views import generic
from .models import Article, Category, MyUser, local_now
from .forms import ArticleEditForm, CategoryEditForm, UserEditForm
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

class IndexView(generic.TemplateView):  # ホーム表示
    template_name = 'core/index.html'

class ArticleDetailView(generic.TemplateView):
    template_name = 'core/article_detail.html'

    def get(self, request, *args, **kwargs):
        pk = self.kwargs.get('pk')
        obj = get_object_or_404(Article, pk=pk)
        if obj.is_published or obj.author == request.user:
            obj.view_count += 1
            obj.save()
            return super().get(request, *args, **kwargs)
        else:
            messages.warning(request, 'アクセスしようとした記事は未公開ですので、ホームにリダイレクトされました。')
            return redirect('core:index')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        article = get_object_or_404(Article, pk=pk)
        context['article'] = article
        # 親が存在しない地点までさかのぼってカテゴリーのリストを作成する
        category = article.category
        category_list = []
        i = 0
        while i < 10 and category is not None:
            i += 1
            category_list.append(category)
            category = category.upper
        category_list.reverse()  # 上位カテゴリを後ろに加えていったので最後にreverse
        context['category_list'] = category_list
        return context

class ArticleCreateView(generic.TemplateView):
    template_name = 'core/article_create.html'

    def post(self, request):
        form = ArticleEditForm(request.POST, request.FILES)
        if form.is_valid:
            post = form.save(commit=False)
            post.pub_date = timezone.localtime(timezone.now())
            post.renew_date = timezone.localtime(timezone.now())
            post.view_count = 0
            post.author = request.user
            post.compose_html()
            post.save()
            messages.success(request, '記事を新しく作成しました。')
            if not post.is_published:
                messages.info(request, '記事は作成されましたが、まだ公開されていません。')
            return redirect('core:index')
        else:
            messages.error(request, '記事を作成できませんでした。')
            return render(request, self.template_name, {'form':form})
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ArticleEditForm()
        return context

class ArticleEditView(generic.TemplateView):
    template_name = 'core/article_edit.html'

    def post(self, request, pk):
        article=Article.objects.get(pk=pk)
        form = ArticleEditForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            article.title = form.cleaned_data['title']
            if form.cleaned_data['thumbnail']:
                article.thumbnail = form.cleaned_data['thumbnail']
            article.content = form.cleaned_data['content']
            article.has_table_of_contents = form.cleaned_data['has_table_of_contents']
            article.is_published = form.cleaned_data['is_published']
            article.lead = form.cleaned_data['lead']
            article.renew_date = local_now()  # 更新時には投稿日やビュー数、著者は更新しない
            # 上記のアップデートされた内容に基づき、htmlを生成してセーブする
            article.compose_html()
            article.save()
            messages.success(request, '記事を更新しました。')
            if not article.is_published:
                messages.info(request, '記事は更新されましたが、まだ公開されていません。')
            return redirect('core:detail', pk=article.pk)
        else:
            messages.error(request, '記事を更新できませんでした。')
            return render(request, self.template_name, {'form':form, 'article': article})
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article = get_object_or_404(Article, pk=self.kwargs.get('pk'))
        context['article'] = article
        context['form'] = ArticleEditForm(instance=article)
        return context

class CategoryCreateView(generic.TemplateView):
    template_name = 'core/category_edit.html'

    def post(self, request):
        form = CategoryEditForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'カテゴリを新しく作成しました。')
            return redirect('core:index')
        else:
            messages.error(request, 'カテゴリを作成できませんでした。')
            return render(request, self.template_name, {'form':form, 'creating_new': True})
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CategoryEditForm()
        context['creating_new'] = True
        return context

class CategoryDetailView(generic.TemplateView):
    template_name = 'core/category_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        inner_name = self.kwargs.get('inner_name')  # 内部カテゴリ名をurlのサブディレクトリとして用いる
        category = get_object_or_404(Category, inner_name=inner_name)
        context['category'] = category
        context['lower_categories'] = category.lowers.all()
        context['articles'] = category.article_set.filter(is_published=True)
        category_list = []
        i = 0
        while i < 10 and category is not None:
            i += 1
            category_list.append(category)
            category = category.upper
        category_list.reverse()  # 上位カテゴリを後ろに加えていったので最後にreverse
        context['category_list'] = category_list
        return context

class CategoryEditView(generic.TemplateView):
    template_name = 'core/category_edit.html'

    def post(self, request, inner_name):
        category = Category.objects.get(inner_name=inner_name)
        form = CategoryEditForm(request.POST, instance=category)
        if form.is_valid():
            category.name = form.cleaned_data['name']
            category.inner_name = form.cleaned_data['inner_name']
            category.upper = form.cleaned_data['upper']
            category.description = form.cleaned_data['description']
            category.is_root = form.cleaned_data['is_root']
            category.save()
            messages.success(request, 'カテゴリを更新しました。')
            return redirect('core:category-detail', inner_name=category.inner_name)
        else:
            messages.error(request, 'カテゴリを更新できませんでした。')
            return render(request, self.template_name, {'form':form, 'inner_name': inner_name, 'creating_new': False})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = get_object_or_404(Category, inner_name=self.kwargs.get('inner_name'))
        context['inner_name'] = category.inner_name
        context['form'] = CategoryEditForm(instance=category)
        context['creating_new'] = False
        return context

class UserEditView(LoginRequiredMixin, generic.TemplateView):
    """
    アイコン画像、表示名、ユーザー名の変更をするビュー
    パスワードの変更はallauthの専用のビューから行う
    """
    template_name = 'core/user_edit.html'

    def post(self, request):
        user = request.user
        form = UserEditForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            if form.cleaned_data['icon']:
                user.icon = form.cleaned_data['icon']
            user.username = form.cleaned_data['username']
            user.display_name = form.cleaned_data['display_name']
            user.save()
            messages.success(request, 'プロフィールを更新しました。')
            return redirect('core:user-detail')
        else:
            messages.error(request, 'プロフィールを更新できませんでした。')
            return render(request, self.template_name, {'form': form})
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = UserEditForm(instance=self.request.user)
        return context

class UserDetailView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'core/user_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['articles'] = Article.objects.filter(author=self.request.user).order_by('renew_date').reverse()
        return context

class AuthorListView(generic.TemplateView):
    template_name = 'core/author_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['authors'] = MyUser.objects.all()
        return context

core/templates/core/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="application-name" content="感覚の数学">
    <meta name="apple-mobile-web-app-title" content="感覚の数学">
    <meta name="author" content="kanyamo">
    <meta name="theme-color" content="#fff">
    <link rel="stylesheet" href="{% static 'core/css/base.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.2/dist/katex.min.css"
        integrity="sha384-bYdxxUwYipFNohQlHt0bjN/LCpueqWz13HufFEV1SUatKs1cm4L6fFgCi1jT643X" crossorigin="anonymous">
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/regular.css' %}" rel="stylesheet" type="text/css">
    <link rel="icon" type="image/x-icon" href="{% static 'core/image/favicon.ico' %}" />
    <link rel="apple-touch-icon" href="{% static 'core/image/apple-touch-icon.png' %}" />
    {% block extra-styles %}{% endblock %}
    {% block structured-data %}{% endblock %}
    <title>{% block title %}{% endblock %}&nbsp;|&nbsp;感覚の数学</title>
</head>

<body class="preload" id="body">
    <header>
        <nav>
            <div class="navigation-home-container">
                <a class="navbar-nav navigation-home" href="{% url 'core:index' %}" accesskey="0" title="HOME: Alt+0">
                    <p class="navbar-nav-title navigation-title-home">感覚の数学</p>
                </a>
                <div class="open-button-container">
                    <div class="open-button" id="open-button">
                        <span class="menu-line"></span>
                        <span class="menu-line"></span>
                        <span class="menu-line"></span>
                        <span class="help-text" id="help-text"></span>
                    </div>
                </div>
            </div>
            <ul class="navbar-list navbar-list-hidden" id="navbar-list">
                {% for category in root_categories %}
                <li class="navbar-list-item">
                    <a class="navbar-nav category" href="{% url 'core:category-detail' category.inner_name %}"
                        accesskey="{{ forloop.counter }}" title="{{ category.name }}: Alt+{{ forloop.counter }}">
                        <p class="navbar-nav-title">{{ category.name }}</p>
                    </a>
                </li>
                {% endfor %}
            </ul>
        </nav>
        {% block extra_header %}{% endblock %}
    </header>
    <div class="wrapper">
        {% if messages %}
        <div class="message-container">
            <ul class="messages">
                {% for message in messages %}
                <li class="{{ message.tags }}">{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        <div class="container">
            {% block contents %}
            {% endblock %}
        </div>
    </div>
    <footer>
        <ul class="footer-list">
            {% if request.user.is_authenticated %}
            <li class="footer-list-item">
                <a href="{% url 'core:user-detail' %}">
                    <p>アカウント</p>
                </a>
            </li>
            <li class="footer-list-item">
                <a href="{% url 'core:article-create' %}">
                    <p>記事作成</p>
                </a>
            </li>
            <li class="footer-list-item">
                <a href="{% url 'core:category-create' %}">
                    <p>カテゴリ作成</p>
                </a>
            </li>
            <li class="footer-list-item">
                <a href="{% url 'account_logout' %}">
                    <p>ログアウト</p>
                </a>
            </li>
            {% endif %}
            <li class="footer-list-item">
                <a href="{% url 'core:author-list' %}">
                    <p>作者一覧</p>
                </a>
            </li>
            <li class="footer-list-item">
                <a href="#">
                    <p>トップに戻る</p>
                </a>
            </li>
        </ul>
    </footer>
    {% block scripts %}
    <script type="text/javascript" src="{% static 'core/js/navbar.js' %}"></script>
    <script type="text/javascript" src="{% static 'core/js/marker.js' %}"></script>
    <script type="text/javascript" src="{% static 'core/js/preload.js' %}"></script>
    {% endblock %}
</body>

</html>

core/templates/core/base/one_column_base.html
{% extends "core/base/base.html" %}
{% block contents %}
<div class="column1-1">
    <main>
        {% block column1-1 %}
        {% endblock %}
    </main>
</div>
{% endblock %}

core/templates/core/base/two_column_base.html
{% extends "core/base/base.html" %} <!-- カラムを2段組にしたいページに適用する -->
{% block contents %}
<div class="column2-1"> <!-- 2つあるカラムの1つめ -->
    <main>
        {% block column2-1 %}
        {% endblock %}
    </main>
</div>
<div class="column2-2">
    <aside>
        <h2>人気記事</h2>
        <div class="article-links">
            {% for article in popular_articles %}
            {% include "core/article_link.html" with article=article %}
            {% endfor %}
        </div>
        <h2>新着記事</h2>
        <div class="article-links">
            {% for article in new_articles %}
            {% include "core/article_link.html" with article=article %}
            {% endfor %}
        </div>
    </aside>
</div>
{% endblock %}